Superhero Creator/Models/ErrorViewModel.cs
using System;

namespace Superhero_Creator.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Superhero Creator/Models/Superhero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Superhero_Creator.Models
{
    public class Superhero
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="Hey dumbass, enter a name")]
        public string Name { get; set; }
        public string AltEgo { get; set; }
        public string PrimAbility { get; set; }
        public string SecAbility { get; set; }
        public string CatchPhrase { get; set; }
    }
}

Superhero Creator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Superhero_Creator.Models;

namespace Superhero_Creator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Superhero Creator/Controllers/SuperheroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Superhero_Creator.Data;
using Superhero_Creator.Models;

namespace Superhero_Creator.Controllers
{
    public class SuperheroController : Controller
    {
        private ApplicationDbContext _context;
        public SuperheroController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: SuperheroController
        public ActionResult Index()
        {
            var superheroes = _context.Superheroes;
            return View(superheroes);
        }
        // GET: SuperheroController/Details/5
        public ActionResult Details(int id)
        {
            var superhero = _context.Superheroes.Find(id);
            return View(superhero);
        }
        // GET: SuperheroController/Create
        public ActionResult Create()
        {
            Superhero superhero = new Superhero();
            return View(superhero);
        }
        // POST: SuperheroController/Create
        [HttpPost]
        public ActionResult Create([Bind("Id,Name,AltEgo,PrimAbility,SecAbility,CatchPhrase")] Superhero superhero)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Superheroes.Add(superhero);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            else
            {
                return View();
            }
        }
        // GET: SuperheroController/Edit/5
        public ActionResult Edit(int id)
        {
            var superhero = _context.Superheroes.Find(id);
            return View(superhero);
        }
        // POST: SuperheroController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Superhero superhero)
        {
            try
            {
                _context.Superheroes.Update(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        // GET: SuperheroController/Delete/5
        public ActionResult Delete(int id)
        {
            var superhero = _context.Superheroes.Find(id);
            return View(superhero);
        }
        // POST: SuperheroController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Superhero superhero)
        {
            try
            {
                _context.Superheroes.Remove(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Superhero Creator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Anime Hero Database</h1>
</div>

Superhero Creator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Superhero Creator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-cyborg.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Superhero Creator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Superhero" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Superhero" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Superhero Creator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Superhero Creator/Views/Superhero/Create.cshtml
@model Superhero_Creator.Models.Superhero

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AltEgo" class="control-label"></label>
                <input asp-for="AltEgo" class="form-control" />
                <span asp-validation-for="AltEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimAbility" class="control-label"></label>
                <input asp-for="PrimAbility" class="form-control" />
                <span asp-validation-for="PrimAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecAbility" class="control-label"></label>
                <input asp-for="SecAbility" class="form-control" />
                <span asp-validation-for="SecAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label"></label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Superhero Creator/Views/Superhero/Delete.cshtml
@model Superhero_Creator.Models.Superhero

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AltEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AltEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatchPhrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Superhero Creator/Views/Superhero/Details.cshtml
@model Superhero_Creator.Models.Superhero

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AltEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AltEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatchPhrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Superhero Creator/Views/Superhero/Edit.cshtml
@model Superhero_Creator.Models.Superhero

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AltEgo" class="control-label"></label>
                <input asp-for="AltEgo" class="form-control" />
                <span asp-validation-for="AltEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimAbility" class="control-label"></label>
                <input asp-for="PrimAbility" class="form-control" />
                <span asp-validation-for="PrimAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecAbility" class="control-label"></label>
                <input asp-for="SecAbility" class="form-control" />
                <span asp-validation-for="SecAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label"></label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Superhero Creator/Views/Superhero/Index.cshtml
@model IEnumerable<Superhero_Creator.Models.Superhero>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                    @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AltEgo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrimAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SecAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CatchPhrase)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">
                @Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AltEgo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrimAbility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SecAbility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CatchPhrase)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>